### ISSUE TITLE
Not 100% sure if sampling parameters is correct

### ISSUE THREAD

**Issue by kirill-fedyanin** [IINemo/lm-polygraph#119]
https://github.com/IINemo/lm-polygraph/blame/00851972311db837de6358c90dac65616495d4de/src/lm_polygraph/stat_calculators/sample.py#L27

It's now setting both top_k=50 and top_p if we just set top_p, if i understand code correctly. Having both top_k and top_p is kind of weird to me.
Also there seems there is no do_sample; from the hf docs, we could accidentaly get contrastive_search() instead of sample()

Would be nice to test this

**Comment by rvashurin** [comment]
Yep, blackbox sampling parameters seem sketchy, we'll need to check them after we're finished with benchmarks.

**Comment by rvashurin** [comment]
@cant-access-rediska0123 why do we set 50 as default topK?

**Comment by IINemo** [comment]
We use default value of huggingface.
