### ISSUE TITLE
Is there a requirement for the Python version to run this repository on a Linux system？

### ISSUE THREAD

**Issue by EdwardChang5467** [IINemo/lm-polygraph#261]
Is there a requirement for the Python version of the runtime environment for installing this repository on a Linux system? I tried 3.9, 3.10, and 3.12 when installing the virtual environment, but all failed at the 'pip install .' step.

**Comment by EdwardChang5467** [comment]
File "/etc/miniconda3/envs/ccp/lib/python3.11/multiprocessing/pool.py", line 774, in get
          raise self._value
      Cython.Compiler.Errors.CompileError: sklearn/ensemble/_hist_gradient_boosting/splitting.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by EdwardChang5467** [comment]
The error message for version 3.12 is as follows:       File "/etc/miniconda3/envs/ccp/lib/python3.11/multiprocessing/pool.py", line 774, in get
          raise self._value
      Cython.Compiler.Errors.CompileError: sklearn/ensemble/_hist_gradient_boosting/splitting.pyx
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by EdwardChang5467** [comment]
I encountered the following issue while executing the 'pip install.' command with python version 3.10.15:
Using cached https://mirror.nju.edu.cn/pypi/web/packages/62/7c/596ff7b32f655f379d3abdfa82607e5cb3b70f46baad4604706511cfeb85/scikit-learn-1.0.1.tar.gz (6.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Partial import of sklearn during the build process.
      Traceback (most recent call last):
        File "/etc/miniconda3/envs/ccp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/etc/miniconda3/envs/ccp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/etc/miniconda3/envs/ccp/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-v7hhtc6e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-v7hhtc6e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-v7hhtc6e/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in run_setup
          exec(code, locals())
        File "<string>", line 319, in <module>
        File "<string>", line 311, in setup_package
        File "/tmp/pip-build-env-v7hhtc6e/overlay/lib/python3.10/site-packages/numpy/distutils/core.py", line 24, in <module>
          from numpy.distutils.command import config, config_compiler, \
        File "/tmp/pip-build-env-v7hhtc6e/overlay/lib/python3.10/site-packages/numpy/distutils/command/config.py", line 19, in <module>
          from numpy.distutils.mingw32ccompiler import generate_manifest
        File "/tmp/pip-build-env-v7hhtc6e/overlay/lib/python3.10/site-packages/numpy/distutils/mingw32ccompiler.py", line 29, in <module>
          from distutils.msvccompiler import get_build_version as get_build_msvc_version
      ModuleNotFoundError: No module named 'distutils.msvccompiler'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

**Comment by IINemo** [comment]
Hi, sorry for the problems. We will check the pip package. You can install using the following command:
```pip install git+https://github.com/IINemo/lm-polygraph```

**Comment by IINemo** [comment]
The Python version should be 3.11

**Comment by SpeedOfMagic** [comment]
> Is there a requirement for the Python version of the runtime environment for installing this repository on a Linux system? I tried 3.9, 3.10, and 3.12 when installing the virtual environment, but all failed at the 'pip install .' step.

Hi! While it's recommended to have Python version 3.11, it is known to have worked for version 3.10.

I've noticed that you are using scikit-learn package of a version 1.0.1. However, in order for lm-polygraph to work, [it's required to use scikit-learn of a version 1.5.1 and above](https://github.com/IINemo/lm-polygraph/blob/31eee79f13ee0dd945524dffd068145e26e8e536/requirements.txt#L4). Could you please update your scikit-learn package and see if a problem persists?

**Comment by EdwardChang5467** [comment]
Thank you for all your replies. After independently installing the required packages for several programs in the virtual environment, I have resolved the issue successfully.

**Comment by EdwardChang5467** [comment]
Thank you for all your replies. After independently installing several packages required for the program in the virtual environment, I have resolved the issue successfully.

**Comment by rvashurin** [comment]
@EdwardChang5467 are you installing the latest version from the main branch? It might be an issue with `spacy>3.8`. We have lowered version for spacy to alleviate a similar problem, you might want to check `requirements.txt` and see if this is what causing the issue.

**Comment by EdwardChang5467** [comment]
> @EdwardChang5467 are you installing the latest version from the main branch? It might be an issue with `spacy>3.8`. We have lowered version for spacy to alleviate a similar problem, you might want to check `requirements.txt` and see if this is what causing the issue.
Thanks for your advice. I rechecked the version of Spacey I installed and found it to be 3.7.5. Now it works.

**Comment by EdwardChang5467** [comment]
> @EdwardChang5467 are you installing the latest version from the main branch? It might be an issue with `spacy>3.8`. We have lowered version for spacy to alleviate a similar problem, you might want to check `requirements.txt` and see if this is what causing the issue.

Thanks for your advice, I rechecked the version of `spacy` I installed and found it to be 3.7.5. Now it works.

**Comment by SpeedOfMagic** [comment]
Looks like your problem is solved, so I'm closing this issue. If you have any further questions, feel free to open this issue again.
