### ISSUE TITLE
How to support VLM?

### ISSUE THREAD

**Issue by Zhitao-He** [IINemo/lm-polygraph#267]
Thank you for this wonderful work, I looked at these examples and lm-polygraph only supports plain text language model testing?

**Comment by IINemo** [comment]
Hi, thank you for your question!

The example with VLM could be found here:
https://github.com/IINemo/lm-polygraph/blob/94ddff56fdf34786de6c7d1652606bde18d4cdf7/examples/simple_vlm.ipynb

We will merge it in a few days.
