### ISSUE TITLE
Perplexity Calculation

### ISSUE THREAD

**Issue by vthost** [IINemo/lm-polygraph#273]
Thank you for providing the code base!
I am wondering if the perplexity is missing an `np.exp`, or is this integrated somewhere before and I am missing it maybe?

**Comment by IINemo** [comment]
Dear Veronika, I think np.exp is just a monotonic function and it does not change the ordering of instances. You will get the same results with or without exponentiation, that is why it might be absent from the code.

**Comment by vthost** [comment]
Thanks! Yes, that's true. I just wanted to make sure I understand what's done in the code so that I don't miss it in case it's hidden somewhere.

**Comment by IINemo** [comment]
If you have any other questions, we would be happy to help.
